### ISSUE TITLE
Rigistration Page

### ISSUE THREAD

**Issue by cseshohag** [mahedee/birds-bazar#7]
Registration page should have 
-->ID [hidden]
-->Email [input box]
-->Password [password box]
-->Confirm password [password box]
-->Registration [button]

**Comment by mahedee** [comment]
What if your user name is your email? @cseshohag

**Comment by cseshohag** [comment]
User name should be email id. Then the user can be marked with mail id. Don't need to add user name.

**Comment by cseshohag** [comment]
Registration page created complete
